### ISSUE TITLE
My feedback for your work.

### ISSUE THREAD

**Issue by Nurjigit-Melis-uulu** [sydykovislam/test-layout-2#1]
1) В навигации при ховере ссылки не меняют состояния (А имено свет).
2) Нету состояния при ховере в "Our Latest Projects"
![image](https://user-images.githubusercontent.com/45354207/61870930-44772d80-af01-11e9-9b58-0e22f1493002.png) 
3) Значения похожие. В макете они другии.
![image](https://user-images.githubusercontent.com/45354207/61871033-8ef8aa00-af01-11e9-9323-864ca335e7ef.png) 
4) При ховере состояния ссылки не должно меняется в "Recent Post".
![image](https://user-images.githubusercontent.com/45354207/61871095-b94a6780-af01-11e9-9221-a5e086d1ec94.png) 

Удачи в в правках!

**Comment by ally-8253** [comment]
По-моеу также не хватает состояние ссылок и кнопок при ховере на всей странице.
И еще вот здесь стрелочки разных цветов. Мне кажется, что один из цветов это как раз таки состояние при ховере, а у тебя получается, что они не меняются.
![image](https://user-images.githubusercontent.com/52468368/61871976-fe6f9900-af03-11e9-8d3f-05689e5a00ba.png)
